#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../@nrwl+tao@14.1.9_typescript@4.7.4/node_modules/@nrwl/tao/index.js" "$@"
else
  exec node  "$basedir/../../../../../@nrwl+tao@14.1.9_typescript@4.7.4/node_modules/@nrwl/tao/index.js" "$@"
fi
