#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../@swc+core@1.2.204/node_modules/@swc/core/run_swcx.js" "$@"
else
  exec node  "$basedir/../../../../../@swc+core@1.2.204/node_modules/@swc/core/run_swcx.js" "$@"
fi
