#!/bin/sh -xv
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# $ git config core.hooksPath
# $ git commit --amend 
# $ echo $(uname -s) >> hook.log 

# for github desktop and bash
# windows - mingw | cygwin

NAME=$(uname -s)

if [[ $NAME =~ ^MINGW* ]] || [[ $NAME =~ ^CYGWIN* ]]; then
    npm.cmd run lint
    npm run prettier
else 
    npm run lint
    npm run prettier
fi
